#!/usr/bin/env python
"""Bootstrap replicate worker for the cluster-parallel LRT.

Called by the SLURM job array generated by run_lrt_cluster.py prepare.
Not intended to be invoked directly.
"""

import argparse
import json
import logging
import os
import pickle
import sys

import torch

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from lrt import compute_lrt_statistic

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

sys.setrecursionlimit(5000)
torch.set_default_dtype(torch.float64)


def main():
    parser = argparse.ArgumentParser(description="LRT bootstrap replicate worker.")
    parser.add_argument("--work_dir", required=True,
                        help="LRT output directory (contains work/ subdirectory).")
    parser.add_argument("--replicate", type=int, required=True,
                        help="Bootstrap replicate index (SLURM_ARRAY_TASK_ID).")
    parser.add_argument("--device", default="cpu")
    args = parser.parse_args()

    b = args.replicate
    device = torch.device(args.device)
    work_dir = os.path.join(args.work_dir, "work")

    with open(os.path.join(work_dir, "meta.pkl"), "rb") as fp:
        meta = pickle.load(fp)

    trees_path = os.path.join(work_dir, "bootstrap_trees", f"{b:04d}.pkl")
    with open(trees_path, "rb") as fp:
        trees = pickle.load(fp)

    result_path = os.path.join(work_dir, "bootstrap_results", f"{b:04d}.json")

    if len(trees) == 0:
        logger.warning("Replicate %d: 0 trees — skipping.", b)
        result = {"lrt_stat": 0.0, "ll_uncon": 0.0, "ll_null": 0.0, "skipped": True}
    else:
        try:
            ll_uncon, ll_null, lrt_stat = compute_lrt_statistic(
                trees=trees,
                n_states=meta["n_states"],
                model_info=meta["model_info"],
                sampling_prob=meta["sampling_prob"],
                constraints=meta["constraints"],
                device=device,
                output_dir=None,
                num_iter_uncon=meta["num_iter_uncon"],
                num_iter_con=meta["num_iter_con"],
                penalty_weight_schedule=meta["penalty_weight_schedule"],
                constraint_tol=meta["constraint_tol"],
                do_logging=False,
            )
            result = {
                "lrt_stat": lrt_stat,
                "ll_uncon": ll_uncon,
                "ll_null": ll_null,
                "skipped": False,
            }
        except RuntimeError as e:
            logger.warning("Replicate %d failed: %s — using LRT=0.", b, e)
            result = {
                "lrt_stat": 0.0,
                "ll_uncon": 0.0,
                "ll_null": 0.0,
                "skipped": True,
                "error": str(e),
            }

    with open(result_path, "w") as fp:
        json.dump(result, fp)
    logger.info("Replicate %d complete: LRT=%.4f", b, result["lrt_stat"])


if __name__ == "__main__":
    main()
